### ISSUE TITLE
[bug] preview website does not work

### ISSUE THREAD

**Issue by sonnyding1** [ai-hermes/doc-solver#28]
Hi there, nice project!

When I tried to use the app in the preview website, nothing happens:

<img width="1512" alt="image" src="https://github.com/ai-hermes/doc-solver/assets/93831983/b83bc9b5-9f78-4373-aff2-37c70633a354">

I wonder if this behavior anticipated? To provide context, I only signed in, I haven't made payment, I didn't see anywhere to upload LLM API keys. I am using Chrome on Mac OS.

**Comment by hehuangz** [comment]
Hi, this was unexpected. We'll fix it as soon as possible. By the way, if you're just using this app, don't make any payments and don't upload any LLM API keys.

**Comment by hehuangz** [comment]
hi, the system has been upgraded and can be used normally. try it HAHA!

**Comment by sonnyding1** [comment]
works like a charm!
